# Site settings
title: Recommendations for IoT Device Manufacturers
description: "Recommendations for IoT Device Manufacturers: Catalog of Features and Mitigations"
baseurl: "/8259-Catalog" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- "*.yml"

# GitHub information will uncomment ones names are finalized and NIST GitHub Pages resources have been allocated
#org_name: usnistgov
#repo_name: nistpages-shell

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Frontmatter
  url: /
  collection: Frontmatter
- text: Catalog
  url: /identity/
  collection: 8259-Catalog
- text: Appendix
  url: /references/
  collection: Appendix 
  
collections:
  Frontmatter:
    output: true
  8259-Catalog:
    output: true
  Appendix:
    output: true

relative_links:
  enabled:     true
  collections: true

#Uncomment when we go live 
host: 0.0.0.0

include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en
